// <auto-generated />
using System;
using KPIAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace KPIAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("KPIAPI.Domain.Entities.KpiDefinition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("RobotId")
                        .HasColumnType("integer");

                    b.Property<string>("Unit")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("ValueType")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RobotId", "Key")
                        .IsUnique();

                    b.ToTable("KpiDefinitions");
                });

            modelBuilder.Entity("KPIAPI.Domain.Entities.KpiMeasurement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool?>("BoolValue")
                        .HasColumnType("boolean");

                    b.Property<decimal?>("DecimalValue")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<long?>("DurationMs")
                        .HasColumnType("bigint");

                    b.Property<long?>("IntValue")
                        .HasColumnType("bigint");

                    b.Property<int>("KpiDefinitionId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("RecordedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("RunEventId")
                        .HasColumnType("integer");

                    b.Property<string>("TextValue")
                        .HasColumnType("text");

                    b.Property<int>("ValueType")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("KpiDefinitionId");

                    b.HasIndex("RunEventId", "KpiDefinitionId");

                    b.ToTable("KpiMeasurements");
                });

            modelBuilder.Entity("KPIAPI.Domain.Entities.Robot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CenterCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("Robots");
                });

            modelBuilder.Entity("KPIAPI.Domain.Entities.RobotDashboardConfig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FilterKpiKey")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("FilterKpiTextEquals")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<int>("HitlItemsAggregation")
                        .HasColumnType("integer");

                    b.Property<string>("HitlItemsKpiKey")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<int>("RobotId")
                        .HasColumnType("integer");

                    b.Property<int>("TotalItemsAggregation")
                        .HasColumnType("integer");

                    b.Property<string>("TotalItemsKpiKey")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTime?>("UpdatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("RobotId")
                        .IsUnique();

                    b.ToTable("RobotDashboardConfigs");
                });

            modelBuilder.Entity("KPIAPI.Domain.Entities.RobotRun", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("EndTimeUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ErrorCode")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime?>("LastHeartbeatUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("Outcome")
                        .HasColumnType("integer");

                    b.Property<int>("RobotId")
                        .HasColumnType("integer");

                    b.Property<string>("RunId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("StartTimeUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("RobotId", "RunId")
                        .IsUnique();

                    b.HasIndex("RobotId", "StartTimeUtc");

                    b.ToTable("RobotRuns");
                });

            modelBuilder.Entity("KPIAPI.Domain.Entities.RunEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CorrelationKey")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Message")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("PayloadJson")
                        .HasColumnType("text");

                    b.Property<int>("RobotRunId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RobotRunId");

                    b.ToTable("RunEvents");
                });

            modelBuilder.Entity("KPIAPI.Domain.Entities.KpiDefinition", b =>
                {
                    b.HasOne("KPIAPI.Domain.Entities.Robot", "Robot")
                        .WithMany("KpiDefinitions")
                        .HasForeignKey("RobotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Robot");
                });

            modelBuilder.Entity("KPIAPI.Domain.Entities.KpiMeasurement", b =>
                {
                    b.HasOne("KPIAPI.Domain.Entities.KpiDefinition", "KpiDefinition")
                        .WithMany("KpiMeasurements")
                        .HasForeignKey("KpiDefinitionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("KPIAPI.Domain.Entities.RunEvent", "RunEvent")
                        .WithMany("KpiMeasurements")
                        .HasForeignKey("RunEventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KpiDefinition");

                    b.Navigation("RunEvent");
                });

            modelBuilder.Entity("KPIAPI.Domain.Entities.RobotDashboardConfig", b =>
                {
                    b.HasOne("KPIAPI.Domain.Entities.Robot", "Robot")
                        .WithOne()
                        .HasForeignKey("KPIAPI.Domain.Entities.RobotDashboardConfig", "RobotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Robot");
                });

            modelBuilder.Entity("KPIAPI.Domain.Entities.RobotRun", b =>
                {
                    b.HasOne("KPIAPI.Domain.Entities.Robot", "Robot")
                        .WithMany("Runs")
                        .HasForeignKey("RobotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Robot");
                });

            modelBuilder.Entity("KPIAPI.Domain.Entities.RunEvent", b =>
                {
                    b.HasOne("KPIAPI.Domain.Entities.RobotRun", "RobotRun")
                        .WithMany("Events")
                        .HasForeignKey("RobotRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RobotRun");
                });

            modelBuilder.Entity("KPIAPI.Domain.Entities.KpiDefinition", b =>
                {
                    b.Navigation("KpiMeasurements");
                });

            modelBuilder.Entity("KPIAPI.Domain.Entities.Robot", b =>
                {
                    b.Navigation("KpiDefinitions");

                    b.Navigation("Runs");
                });

            modelBuilder.Entity("KPIAPI.Domain.Entities.RobotRun", b =>
                {
                    b.Navigation("Events");
                });

            modelBuilder.Entity("KPIAPI.Domain.Entities.RunEvent", b =>
                {
                    b.Navigation("KpiMeasurements");
                });
#pragma warning restore 612, 618
        }
    }
}
